name: flutter_machine_test
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3
  http: ^1.2.0
  dartz: ^0.10.1
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  freezed: ^2.4.6


flutter:

 
  uses-material-design: true

  assets:
  - assets/images/
  

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
